# Generated by Django 4.2.6 on 2023-10-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=40, unique=True)),
                ("imdb_id", models.IntegerField(blank=True, unique=True)),
                ("genres", models.ManyToManyField(blank=True, to="movies.genre")),
                ("tags", models.ManyToManyField(blank=True, to="movies.tag")),
            ],
        ),
    ]
