# Generated by Django 4.2.6 on 2023-10-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_imdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
