# Generated by Django 4.2.6 on 2024-01-12 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cluster",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(4),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
